# Kafka Streams
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.streams.application-id=sentinel-streams
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde

# Influx DB
influx.url=http://influxdb:8086
influx.token=sentinel-influx-admin-token
influx.org=sentinel
influx.bucket=sentinel-metrics
